export const hexedMeadowCards = [
  {
    name: 'Bee-st Buds',
    id: '101',
    race: 'bee',
    life: '1',
    move: '5',
    range: '1',
    attack: '0',
    defense: '1',
    points: '50',
    figures: '4',
    hexes: '1',
  },
  {
    name: 'Queen Bee',
    id: '102',
    race: 'bee',
    life: '3',
    move: '4',
    range: '1',
    attack: '0',
    defense: '3',
    points: '50',
    figures: '1',
    hexes: '1',
  },
  {
    name: 'Spelling Beez',
    id: '103',
    race: 'bee',
    life: '2',
    move: '4',
    range: '1',
    attack: '0',
    defense: '2',
    points: '50',
    figures: '2',
    hexes: '1',
  },
  {
    name: 'ButterFries',
    id: '201',
    race: 'butterfly',
    life: '2',
    move: '3',
    range: '1',
    attack: '1',
    defense: '1',
    points: '50',
    figures: '4',
    hexes: '1',
  },
  {
    name: 'Mama Butterfly',
    id: '202',
    race: 'butterfly',
    life: '5',
    move: '3',
    range: '1',
    attack: '2',
    defense: '4',
    points: '50',
    figures: '1',
    hexes: '1',
  },
  {
    name: 'Buttery Scarwings',
    id: '203',
    race: 'butterfly',
    life: '1',
    move: '5',
    range: '1',
    attack: '3',
    defense: '4',
    points: '50',
    figures: '2',
    hexes: '1',
  },
]