export const hexedMeadowCards = {
  hm101: {
    name: 'Bee-st Buds',
    cardID: 'hm101',
    race: 'bee',
    life: '1',
    move: '5',
    range: '1',
    attack: '0',
    defense: '1',
    points: '50',
    figures: '2',
    hexes: '1',
  },
  hm102: {
    name: 'Queen Bee',
    cardID: 'hm102',
    race: 'bee',
    life: '3',
    move: '4',
    range: '1',
    attack: '0',
    defense: '3',
    points: '50',
    figures: '1',
    hexes: '1',
  },
  hm103: {
    name: 'Spelling Beez',
    cardID: 'hm103',
    race: 'bee',
    life: '2',
    move: '4',
    range: '1',
    attack: '0',
    defense: '2',
    points: '50',
    figures: '2',
    hexes: '1',
  },
  hm201: {
    name: 'ButterFries',
    cardID: 'hm201',
    race: 'butterfly',
    life: '2',
    move: '3',
    range: '1',
    attack: '1',
    defense: '1',
    points: '50',
    figures: '2',
    hexes: '1',
  },
  hm202: {
    name: 'Mama Butterfly',
    cardID: 'hm202',
    race: 'butterfly',
    life: '5',
    move: '3',
    range: '1',
    attack: '2',
    defense: '4',
    points: '50',
    figures: '1',
    hexes: '1',
  },
  hm203: {
    name: 'Buttery Scarwings',
    cardID: 'hm203',
    race: 'butterfly',
    life: '1',
    move: '5',
    range: '1',
    attack: '3',
    defense: '4',
    points: '50',
    figures: '2',
    hexes: '1',
  },
}
